version: '3.8'
# NOTE: this docker compose is only to run the tests, it does not spin upt the development server
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase

