name = "my-sveltekit-app"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-08-27"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".svelte-kit/cloudflare"  # Directory containing the static assets

[build]
command = "npm run build"
watch_dir = "src"

[env.production]
vars = { NODE_ENV = "production" }

[observability]
enabled = true
