# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Unit Tests

on:
  pull_request:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Setup Node
        run: rm package-lock.json ; mv .env.example .env; npm i
      - name: Typescript Checks
        run: npm run check
      - name: Application Builds
        run: npm run build --if-present
      - name: Vitest
        uses: docker-practice/actions-setup-docker@master
        run: npm test:ci

